# Documentation de la V2 : https://learn.netlify.com/en/basics/configuration/

baseurl = "https://talbotgui.github.io/"
languageCode = "fr-fr"
title = "Guillaume TALBOT"
contentdir = "docs"
theme = "hugo-theme-learn"
metaDataFormat= "yaml"

  
[params]
author = "Guillaume TALBOT"
description = "Guillaume TALBOT - mon CV, mes projets et mes id√©es"
#editURL = "https://github.com/talbotgui/pages-hugo/edit/master/docs/"
showVisitedLinks = true
themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]