baseurl = "https://talbotgui.github.io/"
languageCode = "fr-fr"
title = "Guillaume TALBOT"
contentdir = "docs"
theme = "hugo-theme-learn"
metaDataFormat= "yaml"

[params]
# URL to edit current page.
editURL = "https://github.com/talbotgui/pages-hugo/edit/master/docs/"
# Active the search. See doc: need more configuration
search = true
